import { User } from './../../src/modules/user/models/User';
import { PrismaClient, UserRole, UserStatus } from '@prisma/client';
import { v4 as uuidv4 } from 'uuid';
import * as bcrypt from 'bcrypt';

const prisma = new PrismaClient();

async function hashPassword(password: string): Promise<string> {
  return bcrypt.hash(password, 10);
}

async function seedUsers() {
  console.log('Seeding users...');

  // Common password for all test users
  const password = await hashPassword('Password123!');

  const users = [
    {
      id: uuidv4(),
      email: 'admin@artcraft.com',
      username: 'admin',
      password,
      firstName: 'Admin',
      lastName: 'User',
      role: UserRole.ADMIN,
      status: UserStatus.ACTIVE,
      bio: 'System administrator',
      isVerified: true,
      emailVerified: true,
      lastSeenAt: new Date(),
    },
    {
      id: uuidv4(),
      email: 'minh.nguyen@gmail.com',
      username: 'minhnguyen',
      password,
      firstName: 'Minh',
      lastName: 'Nguyen',
      role: UserRole.ARTISAN,
      status: UserStatus.ACTIVE,
      bio: 'Skilled woodworker with 7+ years of experience crafting handmade furniture',
      avatarUrl: 'https://randomuser.me/api/portraits/men/1.jpg',
      isVerified: true,
      emailVerified: true,
      phone: '+84987654321',
      lastSeenAt: new Date(Date.now() - 1000 * 60 * 60),
    },
    {
      id: uuidv4(),
      email: 'trang.le@outlook.com',
      username: 'trang_artisan',
      password,
      firstName: 'Trang',
      lastName: 'Le',
      role: UserRole.ARTISAN,
      status: UserStatus.ACTIVE,
      bio: 'Textile artist specializing in traditional Vietnamese embroidery and modern applications',
      avatarUrl: 'https://randomuser.me/api/portraits/women/2.jpg',
      isVerified: true,
      emailVerified: true,
      phone: '+84912345678',
      lastSeenAt: new Date(Date.now() - 2000 * 60 * 60),
    },
    {
      id: uuidv4(),
      email: 'hai.pham@yahoo.com',
      username: 'craftsman_hai',
      password,
      firstName: 'Hai',
      lastName: 'Pham',
      role: UserRole.ARTISAN,
      status: UserStatus.ACTIVE,
      bio: 'Master bamboo craftsman creating sustainable home goods and furniture',
      avatarUrl: 'https://randomuser.me/api/portraits/men/3.jpg',
      isVerified: true,
      emailVerified: true,
      phone: '+84978563412',
      lastSeenAt: new Date(Date.now() - 4000 * 60 * 60),
    },
    {
      id: uuidv4(),
      email: 'linh.tran@gmail.com',
      username: 'linh_ceramics',
      password,
      firstName: 'Linh',
      lastName: 'Tran',
      role: UserRole.ARTISAN,
      status: UserStatus.ACTIVE,
      bio: 'Ceramic artist creating contemporary pottery inspired by traditional Vietnamese designs',
      avatarUrl: 'https://randomuser.me/api/portraits/women/4.jpg',
      isVerified: true,
      emailVerified: true,
      phone: '+84923456789',
      lastSeenAt: new Date(Date.now() - 3000 * 60 * 60),
    },
    {
      id: uuidv4(),
      email: 'tuan.nguyen@hotmail.com',
      username: 'tuan_jewelry',
      password,
      firstName: 'Tuan',
      lastName: 'Nguyen',
      role: UserRole.ARTISAN,
      status: UserStatus.ACTIVE,
      bio: 'Jewelry maker working with silver and semi-precious stones from northern Vietnam',
      avatarUrl: 'https://randomuser.me/api/portraits/men/5.jpg',
      isVerified: true,
      emailVerified: true,
      phone: '+84965432187',
      lastSeenAt: new Date(Date.now() - 5000 * 60 * 60),
    },
    {
      id: uuidv4(),
      email: 'mai.do@gmail.com',
      username: 'mai_weaver',
      password,
      firstName: 'Mai',
      lastName: 'Do',
      role: UserRole.ARTISAN,
      status: UserStatus.ACTIVE,
      bio: 'Weaver specializing in traditional loom techniques and natural dyes',
      avatarUrl: 'https://randomuser.me/api/portraits/women/6.jpg',
      isVerified: true,
      emailVerified: true,
      phone: '+84934567890',
      lastSeenAt: new Date(Date.now() - 6000 * 60 * 60),
    },
    {
      id: uuidv4(),
      email: 'sarah.johnson@gmail.com',
      username: 'sarah_j',
      password,
      firstName: 'Sarah',
      lastName: 'Johnson',
      role: UserRole.CUSTOMER,
      status: UserStatus.ACTIVE,
      bio: 'Art enthusiast and collector of handcrafted items',
      avatarUrl: 'https://randomuser.me/api/portraits/women/7.jpg',
      isVerified: true,
      emailVerified: true,
      phone: '+14155552671',
      lastSeenAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    },
    {
      id: uuidv4(),
      email: 'david.smith@outlook.com',
      username: 'david_smith',
      password,
      firstName: 'David',
      lastName: 'Smith',
      role: UserRole.CUSTOMER,
      status: UserStatus.ACTIVE,
      bio: 'Interior designer looking for unique handmade pieces',
      avatarUrl: 'https://randomuser.me/api/portraits/men/8.jpg',
      isVerified: true,
      emailVerified: true,
      phone: '+14155552672',
      lastSeenAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    },
    {
      id: uuidv4(),
      email: 'emma.wilson@yahoo.com',
      username: 'emma_w',
      password,
      firstName: 'Emma',
      lastName: 'Wilson',
      role: UserRole.CUSTOMER,
      status: UserStatus.ACTIVE,
      bio: 'Passionate about supporting traditional crafts and artisans',
      avatarUrl: 'https://randomuser.me/api/portraits/women/9.jpg',
      isVerified: true,
      emailVerified: true,
      phone: '+14155552673',
      lastSeenAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    },
    {
      id: uuidv4(),
      email: 'michael.brown@gmail.com',
      username: 'mike_brown',
      password,
      firstName: 'Michael',
      lastName: 'Brown',
      role: UserRole.CUSTOMER,
      status: UserStatus.ACTIVE,
      bio: 'Gift shop owner looking for unique handcrafted inventory',
      avatarUrl: 'https://randomuser.me/api/portraits/men/10.jpg',
      isVerified: true,
      emailVerified: true,
      phone: '+14155552674',
      lastSeenAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    },
    {
      id: uuidv4(),
      email: 'hoang.nguyen@gmail.com',
      username: 'hoang_nguyen',
      password,
      firstName: 'Hoang',
      lastName: 'Nguyen',
      role: UserRole.CUSTOMER,
      status: UserStatus.ACTIVE,
      bio: 'Exploring the world of traditional Vietnamese crafts',
      avatarUrl: 'https://randomuser.me/api/portraits/men/11.jpg',
      isVerified: true,
      emailVerified: true,
      phone: '+84912345677',
      lastSeenAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    },
    {
      id: uuidv4(),
      email: 'ngoc.tran@gmail.com',
      username: 'ngoc_tran',
      password,
      firstName: 'Ngoc',
      lastName: 'Tran',
      role: UserRole.ARTISAN,
      status: UserStatus.INACTIVE,
      bio: 'Lacquer artist on hiatus',
      avatarUrl: 'https://randomuser.me/api/portraits/women/12.jpg',
      isVerified: true,
      emailVerified: true,
      phone: '+84912345655',
      lastSeenAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    },
    {
      id: uuidv4(),
      email: 'tram.le@gmail.com',
      username: 'tram_88',
      password,
      firstName: 'Tram',
      lastName: 'Le',
      role: UserRole.CUSTOMER,
      status: UserStatus.SUSPENDED,
      bio: 'Account currently suspended',
      avatarUrl: null,
      isVerified: true,
      emailVerified: true,
      phone: '+84912345611',
      lastSeenAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000),
    },
    {
      id: uuidv4(),
      email: 'pending@example.com',
      username: 'pending_user',
      password,
      firstName: 'Pending',
      lastName: 'User',
      role: UserRole.CUSTOMER,
      status: UserStatus.ACTIVE,
      bio: 'Account awaiting verification',
      avatarUrl: null,
      isVerified: false,
      emailVerified: false,
      phone: null,
      lastSeenAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    },
  ];

  for (const user of users) {
    await prisma.user.upsert({
      where: { email: user.email },
      update: user,
      create: user,
    });
  }

  console.log(`Seeded ${users.length} users`);
  return users;
}

export { seedUsers };
